# -*- coding: utf-8 -*-
# (c) Copyright 2020 Sensirion AG, Switzerland

##############################################################################
##############################################################################
#                 _____         _    _ _______ _____ ____  _   _
#                / ____|   /\  | |  | |__   __|_   _/ __ \| \ | |
#               | |       /  \ | |  | |  | |    | || |  | |  \| |
#               | |      / /\ \| |  | |  | |    | || |  | | . ` |
#               | |____ / ____ \ |__| |  | |   _| || |__| | |\  |
#                \_____/_/    \_\____/   |_|  |_____\____/|_| \_|
#
#     THIS FILE IS AUTOMATICALLY GENERATED AND MUST NOT BE EDITED MANUALLY!
#
# Generator:    sensirion-shdlc-interface-generator 0.8.2
# Product:      SFC5xxx
# Version:      0.1.0
#
##############################################################################
##############################################################################

# flake8: noqa

from __future__ import absolute_import, division, print_function
from .device_information import \
    Sfc5xxxCmdGetProductType, \
    Sfc5xxxCmdGetProductName, \
    Sfc5xxxCmdGetArticleCode, \
    Sfc5xxxCmdGetSerialNumber, \
    Sfc5xxxCmdGetProductSubtype
from .get_version import \
    Sfc5xxxCmdGetVersion
from .read_device_status import \
    Sfc5xxxCmdReadDeviceStatus
from .device_reset import \
    Sfc5xxxCmdDeviceReset
from .slave_address import \
    Sfc5xxxCmdGetSlaveAddress, \
    Sfc5xxxCmdSetSlaveAddress
from .baudrate import \
    Sfc5xxxCmdGetBaudrate, \
    Sfc5xxxCmdSetBaudrate
from .factory_reset import \
    Sfc5xxxCmdFactoryReset
from .reply_delay import \
    Sfc5xxxCmdGetReplyDelay, \
    Sfc5xxxCmdSetReplyDelay
from .setpoint import \
    Sfc5xxxCmdGetSetpoint, \
    Sfc5xxxCmdSetSetpoint
from .setpoint_persist import \
    Sfc5xxxCmdSetSetpointPersist, \
    Sfc5xxxCmdGetSetpointPersist
from .set_setpoint_and_read_measured_value import \
    Sfc5xxxCmdSetSetpointAndReadMeasuredValue
from .read_measured_value import \
    Sfc5xxxCmdReadMeasuredValue
from .read_measured_value_buffer import \
    Sfc5xxxCmdReadMeasuredValueBuffer
from .valve_input_source_configuration import \
    Sfc5xxxCmdGetValveInputSource, \
    Sfc5xxxCmdSetValveInputSource, \
    Sfc5xxxCmdGetUserDefinedValveValue, \
    Sfc5xxxCmdSetUserDefinedValveValue
from .medium_unit_configuration import \
    Sfc5xxxCmdGetUserDefinedMediumUnit, \
    Sfc5xxxCmdSetUserDefinedMediumUnit, \
    Sfc5xxxCmdGetUserDefinedMediumUnitWithoutWildcards, \
    Sfc5xxxCmdGetUserDefinedFullscale
from .controller_configuration import \
    Sfc5xxxCmdGetUserControllerGain, \
    Sfc5xxxCmdSetUserControllerGain, \
    Sfc5xxxCmdGetPressureDependentGainEnable, \
    Sfc5xxxCmdSetPressureDependentGainEnable, \
    Sfc5xxxCmdGetInletPressureForGainCorrection, \
    Sfc5xxxCmdSetInletPressureForGainCorrection, \
    Sfc5xxxCmdGetGasTemperatureCompensationEnable, \
    Sfc5xxxCmdSetGasTemperatureCompensationEnable, \
    Sfc5xxxCmdGetInletGasTemperatureForCompensation, \
    Sfc5xxxCmdSetInletGasTemperatureForCompensation
from .advanced_measurements import \
    Sfc5xxxCmdMeasureRawFlow, \
    Sfc5xxxCmdMeasureRawThermalConductivity, \
    Sfc5xxxCmdMeasureRawThermalConductivityWithClosedValve, \
    Sfc5xxxCmdMeasureTemperature
from .get_calibration_information import \
    Sfc5xxxCmdGetNumberOfCalibrations, \
    Sfc5xxxCmdGetCalibrationValidity, \
    Sfc5xxxCmdGetCalibrationGasDescription, \
    Sfc5xxxCmdGetCalibrationGasId, \
    Sfc5xxxCmdGetCalibrationGasUnit, \
    Sfc5xxxCmdGetCalibrationFullscale, \
    Sfc5xxxCmdGetCalibrationInitialConditions, \
    Sfc5xxxCmdGetCalibrationRecalibrationConditions, \
    Sfc5xxxCmdGetCalibrationThermalConductivityReference
from .get_current_calibration_information import \
    Sfc5xxxCmdGetCurrentGasDescription, \
    Sfc5xxxCmdGetCurrentGasId, \
    Sfc5xxxCmdGetCurrentGasUnit, \
    Sfc5xxxCmdGetCurrentFullscale, \
    Sfc5xxxCmdGetCurrentInitialCalibrationConditions, \
    Sfc5xxxCmdGetCurrentRecalibrationConditions, \
    Sfc5xxxCmdGetCurrentThermalConductivityReference
from .activate_calibration import \
    Sfc5xxxCmdActivateCalibration
from .user_memory_access import \
    Sfc5xxxCmdReadUserMemory, \
    Sfc5xxxCmdWriteUserMemory
